version: 3

tasks:
  run:
    aliases:
      - run
    desc: "Run application"
    cmds:
      - go run ./cmd

  docx:
    aliases:
      - docx
    desc: "Generate swagger docx"
    cmds:
      - swag init --dir ./cmd,./internal/echo --output ./cmd/docs

  build:
    aliases:
      - build
    desc: "Build docker image"
    cmds:
      - docker build -t zitrax78/bdui .