basePath: /
definitions:
  views.Card:
    properties:
      id:
        type: string
      imageUrl:
        type: string
      isFavorite:
        type: boolean
      isSelected:
        type: boolean
      price:
        type: number
      quantity:
        type: string
      title:
        type: string
    type: object
  views.SWGCardListResponse:
    properties:
      cards:
        items:
          $ref: '#/definitions/views.Card'
        type: array
    type: object
  views.SWGErrorResponse:
    properties:
      error:
        example: something went wrong
        type: string
    type: object
  views.SWGSuccessResponse:
    properties:
      answer:
        example: operation successful
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: help@breezy.su
    name: Alex "bustard" Provor
    url: https://breezy.su
  title: Card crud for test bdui
  version: test
paths:
  /api/card/all:
    get:
      description: Возвращает список всех карточек
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.SWGCardListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
      summary: Получить все карточки
      tags:
      - cards
  /api/card/all/limit:
    get:
      description: Возвращает список карточек с пагинацией
      parameters:
      - description: Начальная позиция (offset)
        in: query
        name: from
        type: integer
      - description: Конечная позиция
        in: query
        name: to
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.SWGCardListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
      summary: Получить все карточки
      tags:
      - cards
  /api/card/create:
    post:
      consumes:
      - application/json
      description: Добавляет новый card
      parameters:
      - description: Данные нового card
        in: body
        name: brand
        required: true
        schema:
          $ref: '#/definitions/views.Card'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.SWGSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
      summary: Создать новый card
      tags:
      - cards
  /api/card/delete:
    delete:
      description: Удаляет card по ID
      parameters:
      - description: ID card
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.SWGSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
      summary: Удалить card
      tags:
      - cards
  /api/card/update:
    put:
      consumes:
      - application/json
      description: Обновляет информацию о card по ID
      parameters:
      - description: ID card
        in: query
        name: id
        required: true
        type: string
      - description: Данные card
        in: body
        name: brand
        required: true
        schema:
          $ref: '#/definitions/views.Card'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.SWGSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/views.SWGErrorResponse'
      summary: Обновить card
      tags:
      - cards
schemes:
- http
swagger: "2.0"
