services:
    carddb:
        container_name: carddb
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        restart: unless-stopped
        env_file: .env
    card:
        container_name: card
        image: card:latest
        ports:
            - "8080:8080"
        volumes:
            - ./configs:/app/configs  
        environment:
            CONFIG_FILE: card.yaml
        restart: unless-stopped

volumes:
  postgres-data: