version: 3

tasks:
  up:
    aliases:
      - up
    cmds:
      - go run ./cmd/migrator
  down:
    aliases:
      - down
    cmds:
      - go run ./cmd/migrator --type down
  run:
    aliases:
      - run
    desc: "Run application"
    cmds:
      - go run ./cmd/main

  build:
    aliases:
      - build
    desc: "Build docker image"
    cmds:
      - docker build -t card .


  docx:
    aliases:
      - docx
    desc: "Generate swagger docx"
    cmds:
      - swag init --dir ./cmd/main,./internal/echo/,./internal/views --output ./cmd/docs
