// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Alex \"bustard\" Provor",
            "url": "https://breezy.su",
            "email": "admin@breezy.su"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/screen/all": {
            "get": {
                "description": "Returns all screen documents.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "screens"
                ],
                "summary": "List screens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/echo.SWGScreen"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGError"
                        }
                    }
                }
            }
        },
        "/api/screen/create": {
            "post": {
                "description": "Creates a new screen document; server generates UUID and returns it as ` + "`" + `id` + "`" + `.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "screens"
                ],
                "summary": "Create screen",
                "parameters": [
                    {
                        "description": "Screen payload",
                        "name": "screen",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/echo.SWGScreen"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGCreatedID"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGError"
                        }
                    }
                }
            }
        },
        "/api/screen/delete": {
            "delete": {
                "description": "Deletes a screen document by its UUID (` + "`" + `id` + "`" + `).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "screens"
                ],
                "summary": "Delete screen by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Screen ID (UUID)",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGError"
                        }
                    }
                }
            }
        },
        "/api/screen/get": {
            "get": {
                "description": "Returns a single screen document by UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "screens"
                ],
                "summary": "Get screen by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Screen ID (UUID)",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGScreen"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGError"
                        }
                    }
                }
            }
        },
        "/api/screen/rewrite": {
            "put": {
                "description": "Updates fields of a screen document by UUID using ` + "`" + `$set` + "`" + ` semantics.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "screens"
                ],
                "summary": "Update (rewrite) screen by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Screen ID (UUID)",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Fields to set",
                        "name": "screen",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/echo.SWGScreen"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.SWGError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "echo.SWGCreatedID": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "echo.SWGError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "description of error"
                }
            }
        },
        "echo.SWGScreen": {
            "type": "object",
            "additionalProperties": true
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "--dev--",
	Host:             "31.56.205.210:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "bdUI REST API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
